env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {   
  "no-bitwise": "off",
  "no-plusplus": "off",
  "no-empty-pattern": "off",
  "comma-dangle": "off"
}
